default_inputs = {
    'basis': 'cc-pvdz',
    'gauge': 'length',
    'dt': 1e-1,
    'laser_approx': 'dipole',
    'custom_basis': False,
    'initial_time': 0.0,
    'final_time': 10.0,
    'initial_state': None,
    'integrator': 'GaussIntegrator',
    'quadratic_terms': True,
    'cross_terms': True,
    'charge': 0,
    'verbose': False,
    'sample_laser_pulse': False,
    'sample_energy': False,
    'sample_dipole_moment': True,
    'sample_quadrupole_moment':False,
    'sample_momentum': False,
    'sample_kinetic_momentum': False,
    'sample_auto_correlation': False,
    'sample_EOM_projectors': False,
    'sample_EOM2_projectors': False,
    'sample_LR_projectors': False,
    'load_all_response_vectors': False,
    'return_final_state': True,
    'sample_dipole_response': False,
    'sample_general_response': False,
}
